### ISSUE TITLE
Missing Links to CR Privacy Policies

### ISSUE THREAD

**Issue by ginnyfahs** [bocoup/ccpa-authorized-agent#17]
There should be hyperlinks to the following:

- CR Privacy Policy
- CR User Agreement
- SMS/Text Notification Terms
- SMS Privacy Policy

Screen Shot 2021-02-04 at 3.43.35 PM

**Comment by jesdaigle** [comment]
D'oh! This one is on me @ginnyfahs I meant to do this earlier and got lost in making the plan. I'll fix it. :)

**Comment by ginnyfahs** [comment]
Awesome, thank you!

**Comment by jesdaigle** [comment]
![image](https://user-images.githubusercontent.com/30808963/107246186-fdc32880-69fd-11eb-86d5-32063b8241c6.png)
