### ISSUE TITLE
No confirmation text received

### ISSUE THREAD

**Issue by ginnyfahs** [bocoup/ccpa-authorized-agent#18]
I filled out the sign up form on Safari on my MacBook pro. I put in my number as XXXXXXXXXX format. It's been ~30 minutes and still no confirmation text.

**Comment by jesdaigle** [comment]
Ginny did you receive an email to confirm your email address and click the link it contains? That is what triggers the text.

**Comment by ginnyfahs** [comment]
Yes, I clicked the email confirmation link no problem.

So the text from Twilio did eventually get here. It just took over an hour to arrive...

**Comment by alflennik** [comment]
@ginnyfahs Now that we're using a paid SMS account we believe the issue is fixed. Please let us know if you see any delays in the future!
