### ISSUE TITLE
Admin portal Personal Info values should be comma separated

### ISSUE THREAD

**Issue by ginnyfahs** [bocoup/ccpa-authorized-agent#20]
To easily wrangle and sort this data in a spreadsheet, we need standard comma separation of all personal info

For example, a current entry in the table is `Ginny Fahs, Ginny.Fahs.consultant@consumer.org +14045507055` 

It should be `Ginny Fahs, Ginny.Fahs.consultant@consumer.org, +14045507055`

Let me know if you have Qs about what we need here - thanks!

**Comment by alflennik** [comment]
Good point! The fix will be in the next release 👍

**Comment by alflennik** [comment]
Verified as fixed
