### ISSUE TITLE
Signups do not appear in chronological order in admin screen

### ISSUE THREAD

**Issue by ginnyfahs** [bocoup/ccpa-authorized-agent#26]
Table should be sorted as CR ID lowest to highest. Currently it is not sorted that way.

<img width="1051" alt="Screen Shot 2021-02-07 at 11 22 03 AM" src="https://user-images.githubusercontent.com/26640476/107152672-246a5c00-6937-11eb-931b-eae993e0231d.png">

**Comment by jesdaigle** [comment]
Fixed
