### ISSUE TITLE
Address entry fields in POA should be consolidated

### ISSUE THREAD

**Issue by ginnyfahs** [bocoup/ccpa-authorized-agent#29]
In user testing this morning, users were confused about what to use each of the blanks for in the form address entry.

To mitigate, we can change to 1 long line as the address form field, instead of the 4 boxes we currently have. 

<img width="746" alt="Screen Shot 2021-02-04 at 4 26 45 PM" src="https://user-images.githubusercontent.com/26640476/107152907-a313c900-6938-11eb-82fd-b4b1422db881.png">

**Comment by alflennik** [comment]
@jesdaigle I believe this is already on your radar!

**Comment by jesdaigle** [comment]
![image](https://user-images.githubusercontent.com/30808963/107251605-85129b00-6a02-11eb-90c2-1802bd809d50.png)
