### ISSUE TITLE
MAILGUN_SENDER should be datarightsstudy@cr.org

### ISSUE THREAD

**Issue by ginnyfahs** [bocoup/ccpa-authorized-agent#32]
And I'm in the process of verifying the @cr.org domain so that this will all work smoothly. Thanks!

**Comment by alflennik** [comment]
Hi Ginny, thank you for this information! Keep us informed of your progress! 🙂

**Comment by alflennik** [comment]
Updated! And the real CR Mailgun account is now in use.
